# Generated by Django 5.2.8 on 2025-11-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='id_document',
            field=models.URLField(),
        ),
    ]
