# Generated by Django 5.2.8 on 2025-11-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_identityverification_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.URLField(blank=True, default='https://247nigeria.s3.eu-north-1.amazonaws.com/cover-photo.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
