# Generated by Django 5.2.8 on 2025-11-30 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_cover_photo_alter_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('design', 'Design'), ('graphics', 'Graphics'), ('customer_service', 'Customer Service'), ('other', 'Other')], max_length=50)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50)),
                ('full_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('requirements', models.TextField()),
                ('key_responsibilities', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField(help_text='Required years of experience')),
                ('education', models.CharField(max_length=255)),
                ('minimum_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_period', models.CharField(choices=[('per_month', 'Per Month'), ('per_hour', 'Per Hour'), ('per_year', 'Per Year')], max_length=20)),
                ('application_method', models.CharField(choices=[('phone', 'Via Phone Number'), ('email', 'Via Email'), ('external_link', 'External Link')], max_length=20)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_jobs', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_thumbnail', models.BooleanField(default=False, help_text='Mark as main thumbnail image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.job')),
            ],
            options={
                'verbose_name': 'Job Image',
                'verbose_name_plural': 'Job Images',
                'ordering': ['order', '-is_thumbnail', 'uploaded_at'],
            },
        ),
    ]
