# Generated by Django 5.2.8 on 2025-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_method',
            field=models.CharField(choices=[('phone', 'Via Phone Number'), ('email', 'Via Email'), ('external_link', 'External Link'), ('onsite', 'onsite')], max_length=20),
        ),
    ]
