# Generated by Django 5.2.8 on 2025-12-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_job_application_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicant_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of applicants'),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_method',
            field=models.CharField(choices=[('phone', 'Via Phone Number'), ('email', 'Via Email'), ('external_link', 'External Link'), ('onsite', 'Apply on Site')], max_length=20),
        ),
    ]
