# Generated by Django 5.2.8 on 2025-12-10 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_job_applicant_count_alter_job_application_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('land', 'Land'), ('commercial_building', 'Commercial Building'), ('office_space', 'Office Space')], max_length=50)),
                ('listing_type', models.CharField(choices=[('for_rent', 'For Rent'), ('for_sale', 'For Sale'), ('for_lease', 'For Lease')], max_length=50)),
                ('full_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('size_sqm', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=10)),
                ('parking_spots', models.PositiveIntegerField(default=0)),
                ('property_description', models.TextField()),
                ('furnishing_status', models.CharField(choices=[('fully_furnished', 'Fully Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=50)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_period', models.CharField(choices=[('per_month', 'Per Month'), ('per_year', 'Per Year'), ('one_time', 'One Time Payment')], max_length=20)),
                ('contact_method', models.CharField(choices=[('phone', 'Via Phone Number'), ('email', 'Via Email'), ('external_link', 'External Link')], max_length=20)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inquiry_count', models.PositiveIntegerField(default=0, help_text='Number of inquiries')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('is_thumbnail', models.BooleanField(default=False, help_text='Mark as main thumbnail image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', '-is_thumbnail', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(help_text='Inquiry message from the interested party')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Budget of the inquirer', max_digits=12, null=True)),
                ('move_in_date', models.DateField(blank=True, help_text='Preferred move-in date', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('deal_closed', 'Deal Closed')], default='pending', max_length=20)),
                ('inquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_inquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='accounts.property')),
            ],
            options={
                'verbose_name': 'Property Inquiry',
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-inquired_at'],
                'unique_together': {('property', 'inquirer')},
            },
        ),
    ]
